### ISSUE TITLE
Leaderboard commands not working

### ISSUE THREAD

**Issue by timmermansjoy** [TheFutureGadgetsLab/AdventOfCodeBot#2]
when running the program the it gives errors when it gets an request

when printing the person it does show 

```
Ignoring exception in command clb:
Traceback (most recent call last):
  File "/Users/Joy/Desktop/AdventOfCodeBot/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/Joy/Desktop/AdventOfCodeBot/main.py", line 37, in clb
    leaderboard = Leaderboard(db)
  File "/Users/Joy/Desktop/AdventOfCodeBot/src/Leaderboard.py", line 17, in __init__
    self.merge_shelf(db)
  File "/Users/Joy/Desktop/AdventOfCodeBot/src/Leaderboard.py", line 57, in merge_shelf
    if player.name.lower() not in registered_players:
AttributeError: 'NoneType' object has no attribute 'lower'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Joy/Desktop/AdventOfCodeBot/.venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/Users/Joy/Desktop/AdventOfCodeBot/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/Users/Joy/Desktop/AdventOfCodeBot/.venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by haydn-jones** [comment]
We'll investigate this today. I see you ran `!clb`, have you registered any users in the bot yet? Just trying to get an idea of all the commands you ran.

**Comment by bensonalec** [comment]
Hi, I believe what's likely causing this is an anonymous user on the scoreboard. We're working to get a patch out for it, thanks for your patience

**Comment by haydn-jones** [comment]
Related issue #3

**Comment by bensonalec** [comment]
Issue should be fixed now! Closing this issue.
